
#        server.port: 8082
#        server:
#          servlet:
#            context-path: /girl

#server:
#  port: 8080
#  servlet:
#    context-path: /girl
#
#girl:
#    cupSize: B
#    age: 18

spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true